import time

from fpdf import FPDF


class ReportPDF(FPDF):
    """Clean, mechanic-ready PDF layout. Header/footer on every page,
    monospace body so codes and numbers line up like a real printout."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(20, 20, 20)
        self.cell(0, 10, "AUTOPI VEHICLE REPORT", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(40, 160, 80)
        self.set_line_width(0.6)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, "Generated by AutoPi - Page " + str(self.page_no()),
                  align="C")

    def section(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 110, 60)
        self.ln(3)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(20, 20, 20)

    def body_line(self, text):
        self.set_font("Courier", "", 10)
        self.multi_cell(w=self.epw, h=5, text=str(text))


class ReportView:
    """Generates the shareable vehicle report. Composes the Logger (data),
    AnomalyDetector (ML), and AIClient (plain-English summary) - the View
    orchestrates them but each Model does its own work (separation)."""

    def __init__(self, logger, detector, ai_client, filename="car_report.txt",
                 pdf_filename="car_report.pdf"):
        self._logger = logger
        self._detector = detector
        self._ai_client = ai_client
        self._filename = filename
        self._pdf_filename = pdf_filename

    def __build_ai_summary(self, summary, events, anomaly_count):
        # Build a compact facts string, ask the AI to summarize it
        facts = ""
        facts += "Total readings: " + str(summary[0]) + ". "
        facts += "Coolant temp range: " + str(summary[1]) + " to " + str(summary[2]) + " C. "
        facts += "Voltage range: " + str(summary[3]) + " to " + str(summary[4]) + " V. "
        facts += "Peak RPM: " + str(summary[5]) + ". Peak boost: " + str(summary[6]) + " PSI. "
        facts += "Trouble codes: "
        if events:
            for ev in events:
                facts += ev[1] + " "
        else:
            facts += "none. "
        if anomaly_count is not None:
            facts += "ML flagged " + str(anomaly_count) + " anomalous readings. "
        return self._ai_client.summarize(facts)

    def generate(self):
        # Pull everything from the Models, write the report file.
        summary = self._logger.get_reading_summary()
        events = self._logger.get_events()
        anomaly_count, ml_note = self._detector.count_anomalies()

        f = open(self._filename, "w")
        f.write("=== AUTOPI VEHICLE REPORT ===\n")
        f.write("Generated: " + time.strftime("%Y-%m-%d %H:%M:%S") + "\n\n")

        # AI summary (baked in)
        f.write("--- AI HEALTH SUMMARY ---\n")
        f.write(str(self.__build_ai_summary(summary, events, anomaly_count)) + "\n\n")

        # ML anomaly analysis (baked in)
        f.write("--- ML ANOMALY ANALYSIS ---\n")
        if anomaly_count is not None:
            f.write("Anomalous readings detected: " + str(anomaly_count) + "\n")
        if ml_note:
            f.write("Note: " + ml_note + "\n")
        f.write("\n")

        # Sensor summary
        f.write("--- SENSOR SUMMARY ---\n")
        f.write("Total readings logged: " + str(summary[0]) + "\n")
        f.write("Coolant temp min/max: " + str(summary[1]) + " / " + str(summary[2]) + "\n")
        f.write("Voltage min/max: " + str(summary[3]) + " / " + str(summary[4]) + "\n")
        f.write("Peak RPM: " + str(summary[5]) + "\n")
        f.write("Peak boost (PSI): " + str(summary[6]) + "\n\n")

        # Trouble codes
        f.write("--- TROUBLE CODES ---\n")
        if events:
            for ev in events:
                f.write(ev[1] + " - " + ev[2] + " (" + ev[0] + ")\n")
                f.write("   Explanation: " + str(ev[3]) + "\n")
                f.write("   Fix: " + str(ev[4]) + "\n\n")
        else:
            f.write("No trouble codes recorded.\n")

        f.close()
        print("Report written to", self._filename)
        return self._filename

    def generate_pdf(self):
        # Same data as generate(), formatted as a clean shareable PDF.
        summary = self._logger.get_reading_summary()
        events = self._logger.get_events()
        anomaly_count, ml_note = self._detector.count_anomalies()

        pdf = ReportPDF()
        pdf.add_page()

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(0, 6, "Generated: " + time.strftime("%Y-%m-%d %H:%M:%S"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(20, 20, 20)

        pdf.section("AI HEALTH SUMMARY")
        pdf.body_line(self.__build_ai_summary(summary, events, anomaly_count))

        pdf.section("ML ANOMALY ANALYSIS")
        if anomaly_count is not None:
            pdf.body_line("Anomalous readings detected: " + str(anomaly_count))
        if ml_note:
            pdf.body_line("Note: " + str(ml_note))

        pdf.section("SENSOR SUMMARY")
        pdf.body_line("Total readings logged: " + str(summary[0]))
        pdf.body_line("Coolant temp min/max: " + str(summary[1]) + " / " + str(summary[2]))
        pdf.body_line("Voltage min/max:      " + str(summary[3]) + " / " + str(summary[4]))
        pdf.body_line("Peak RPM:             " + str(summary[5]))
        pdf.body_line("Peak boost (PSI):     " + str(summary[6]))

        pdf.section("TROUBLE CODES")
        if events:
            for ev in events:
                pdf.set_font("Courier", "B", 10)
                pdf.multi_cell(w=pdf.epw, h=5,
                               text=ev[1] + " - " + str(ev[2]) + " (" + ev[0] + ")")
                pdf.body_line("   Explanation: " + str(ev[3]))
                pdf.body_line("   Fix: " + str(ev[4]))
                pdf.ln(1)
        else:
            pdf.body_line("No trouble codes recorded.")

        pdf.output(self._pdf_filename)
        print("PDF written to", self._pdf_filename)
        return self._pdf_filename

    def generate_all(self):
        # Write BOTH the txt and the PDF in one call.
        self.generate()
        self.generate_pdf()
        return self._pdf_filename